export type Trust = "unknown" | "none" | "marginal" | "full" | "ultimate";

export interface KeyInfo {
  fingerprint: string;
  key_id: string;
  name: string | null;
  comment: string | null;
  email: string | null;
  ownertrust: Trust;
  /** Computed validity through the web of trust */
  validity: Trust;
  user_ids: string[];
  algorithm: string;
  /** Unix seconds */
  created: number;
  /** Unix seconds, null = never expires */
  expires: number | null;
  has_secret: boolean;
  /** Secret key material is protected by a passphrase */
  secret_encrypted: boolean;
  revoked: boolean;
}

export type Algorithm = "ed25519" | "rsa4096";

export interface GenerateKeyRequest {
  name: string;
  email: string;
  comment?: string;
  passphrase?: string;
  algorithm: Algorithm;
  /** Validity in days; omit for no expiration */
  validity_days?: number;
}

export interface EncryptRequest {
  input_path: string;
  output_path?: string;
  recipients: string[];
  sign_with?: string;
  passphrase?: string;
  armor: boolean;
}

export interface DecryptRequest {
  input_path: string;
  output_path?: string;
  passphrase?: string;
}

export type SignatureStatus =
  | { status: "valid"; fingerprint: string; signer: string | null }
  | { status: "invalid"; fingerprint: string | null }
  | { status: "unknown_signer"; fingerprint: string | null };

export interface DecryptResult {
  output_path: string;
  signatures: SignatureStatus[];
}

export interface TextDecryptResult {
  text: string;
  signatures: SignatureStatus[];
}

export interface Progress {
  job: string;
  done: number;
  total: number;
}

/** Shape of errors rejected by every backend command. */
export interface AppError {
  code:
    | "wrong_passphrase"
    | "passphrase_required"
    | "missing_recipient"
    | "key_not_found"
    | "no_secret_key"
    | "no_signing_key"
    | "nothing_to_do"
    | "corrupted"
    | "invalid_input"
    | "network"
    | "not_found"
    | "qr_too_large"
    | "io"
    | "other";
  message: string;
}

export interface SubkeyInfo {
  fingerprint: string;
  key_id: string;
  algorithm: string;
  purposes: ("certify" | "sign" | "encrypt" | "authenticate")[];
  created: number;
  expires: number | null;
  is_primary: boolean;
  revoked: boolean;
}

export interface KeyDetail {
  info: KeyInfo;
  subkeys: SubkeyInfo[];
}

export type ServerId = "keys_openpgp_org" | "keyserver_ubuntu_com";
export type CertLevel = "none" | "casual" | "careful";

export interface RemoteKey {
  info: KeyInfo;
  armored: string;
  already_have: boolean;
}

export interface UploadReport {
  fingerprint: string;
  emails: { email: string; status: "published" | "pending" | "unpublished" | "revoked" | string }[];
  verification_requested: boolean;
}

export interface RefreshReport {
  checked: number;
  unchanged: number;
  not_found: number;
  changes: { fingerprint: string; label: string; change: "revoked" | "updated" }[];
}

export interface GraphNode {
  id: string;
  label: string;
  email: string | null;
  ownertrust: Trust;
  validity: Trust;
  is_own: boolean;
  revoked: boolean;
}
export interface GraphEdge {
  from: string;
  to: string;
  weight: "full" | "marginal" | "none";
}
export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export type QrMode = "fingerprint" | "key" | "url";
export interface QrView {
  payload: string;
  /** Trusted SVG generated by the backend */
  svg: string;
  version: number;
  ec: "L" | "M";
  bytes: number;
}

export interface Team {
  id: string;
  name: string;
  /** Key fingerprints; may reference keys that were deleted since */
  members: string[];
}
